language: d
sudo: false

before_script:
    - mysql -e 'SHOW VARIABLES LIKE "%version%";'
    - mysql -e 'CREATE DATABASE mysqln_testdb;'
    - echo 'host=127.0.0.1;port=3306;user=root;pwd=;db=mysqln_testdb' > testConnectionStr.txt

install: ./travis-install-deps.sh
script: ./run-tests

matrix:
    include:
        - d: dmd
          addons:
            mariadb: '10.1'

        - d: dmd-2.073.0
          addons:
            mariadb: '10.1'

        - d: dmd-2.072.2
          addons:
            mariadb: '10.1'

        - d: dmd-2.071.2
          addons:
            mariadb: '10.1'

        - d: dmd-2.070.2
          addons:
            mariadb: '10.1'

        - d: dmd-2.070.2
          addons:
            mariadb: '5.5'
          env: DB=mariadb-5.5

        - d: dmd-2.070.2
          services:
            - mysql
          env: DB=mysql-default

        - d: dmd-2.069.2
          addons:
            mariadb: '10.1'

        - d: dmd-2.068.2
          addons:
            mariadb: '10.1'

        - d: ldc
          addons:
            mariadb: '10.1'

        - d: ldc-0.17.1
          addons:
            mariadb: '10.1'

        - d: ldc-0.17.0
          addons:
            mariadb: '10.1'

        - d: gdc
          addons:
            mariadb: '10.1'

        - d: gdc-4.8.5
          addons:
            mariadb: '10.1'

    #allow_failures:
    #    - d: gdc
