# Builds the documentation, with the latest adrdox, with every push to master,
# and deploys it to the gh-pages branch. Derived from Paul Backus'
# https://github.com/pbackus/sumtype/blob/master/.github/workflows/docs.yml.

name: Documentation

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest

      - name: Build documentation
        run: |
          wget https://github.com/adamdruppe/adrdox/archive/master.zip
          unzip master.zip
          pushd adrdox-master && make && popd
          export PATH=$PATH:$PWD/adrdox-master
          doc2 --genSearchIndex --genSource -o generated-docs source

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: generated-docs